name = "klim-kali-site"
compatibility_date = "2026-08-16"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
keep_vars = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Production Environment
[env.production]
name = "kali-mata-mandir-prod"

# D1 Database for Production
[[env.production.d1_databases]]
binding = "DB"
database_name = "kali-mata-prod-db"
migrations_dir = "db_migrations"

# Send Email Binding for Production
[[env.production.send_email]]
name = "SEB"
